# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_destination_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
