# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_destination_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destination',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
