# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160722_1150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='destination',
            managers=[
                ('tripManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
